[package]
name = "truthdb"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/truthdb_core",
]

[workspace.dependencies]
rstest = "0.26.1"

[dependencies]
tracing = "0.1"
signal-hook = "0.4.1"
truthdb_core = { path = "crates/truthdb_core", version = "0.1.0" }

[profile.dev.package."*"]
opt-level = 3
debug = false

[profile.dev.package.truthdb_core]
debug = 2
