name: Build and test truthdb

on:
  push:
    tags:
      - '*.*.*'

jobs:
    build-test-publish:
        uses: ./.github/workflows/build-test-truthdb.yml
        with:
          publish_artifact: true
    