name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    container:
      image: rust:stable

    steps:
    - name: Cleanup
      uses: FraBle/clean-after-action@v1

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build debug
      run: cargo build --verbose --workspace

    - name: Run tests debug
      run: cargo test --verbose --workspace
    
    - name: Build release
      run: cargo build --release --verbose --workspace 

    - name: Run tests release
      run: cargo test --release --verbose --workspace